config:
  name: ???
  description: ???
  vpc_id: ???
  ingress_cidr_blocks: ???
  ingress_rules:  ???
  egress_rules:  [ "all-all" ]
  tags:
    Name: ???
    Owner: "Hunter-Labs"

providers:
  # Set the provider that will create the infrastructure
  default_provider: "${build.default_provider}"

  # Atlas does not support direct creation of SGs
  atlas:

  TerraGen:
    module_url: "https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest"
    module_source: "terraform-aws-modules/security-group/aws"
    module_version: "~> 3.0"

    s3_backend_key: "common/security_groups/terraform.tfstate"

