defaults:
  - ec2_base



# Overrides of ec2_base config
terraform_config:
  tfvars_file:
    filename: "enginetier.tfvars"
  s3_backend_key : "middleware/ec2/enginetier/terraform.tfstate"

tfvars_config:
  instance_name: "enginetier_${build.environment}"
  instance_type: "${enginetier.environments.${build.environment}.instance_type}"
  tags:
    tag_identifier: "enginetier"

  security_group:
    sg_name: "enginetier_sg"
    sg_description: "SG for Engine Tier"

  key_pair:
    key_name: "engine-key"
