config:
  default_key_pair:
    key_name: "labs-key"
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsYO2EwLo9GQxVoDKdxxQSNw/Y9bukRO6YNpc3MPmKPQorbpawHqYsq15j2/48dHJqP4VUgSwEEcpl/L5zeRRFGxbb3Unf5IdSvCA9aHZSAVfpHZaJVN7Nf0pC3eRKSfYvu166KpoienQg8aswXCgildLb5MDfl7ul6tfrjd/rbyty58Jp51fPKvqpKS0mUn5MT6ToECBtubCEJ9xqupQ5qQpKIHVleSUy+tSAxvYQTuMAmQfYEVQrJn9W9T5dsyWUi4X1MeEri4xqN8ZqaM8lhXmqp0f/Bsjpa15dMjTOkWDadu44dC3lPgB5yW5dcQMtrGMA2LpEvSFhy91iJ9xmw== rsa-key-20210324"

# provider specific config can be added here
providers:
  # Set the provider that will create the infrastructure
  default_provider: "${build.default_provider}"

  # Atlas does not support creation of VPCs
  atlas:

  terraform:
      s3_backend_key: "common/key_pairs/terraform.tfstate"
      tfvars_file:
        path: "C:/dev/python/terravarmer/tfvars"
        filename: "key_pairs.tfvars"
