module_metadata:
  aws_service: "security_groups"
  name: "base_security_group"
  lookup: "base.security_group"
  module_url: "https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest"
  module_source: "terraform-aws-modules/security-group/aws"
  module_version: "~> 3.0"

config:
  name: ???
  description: ???
  vpc_id: ???
  ingress_cidr_blocks: ???
  ingress_rules:  ???
  egress_rules:  [ "all-all" ]
  tags:
    Name: ???
    Owner: "Hunter-Labs"

outputs:
  this_security_group_id:
    description: "The ID of the security group"
    lookup: "${...module_metadata.lookup}.outputs.this_security_group_id"

providers:
  # Set the provider that will create the infrastructure
  default_provider: "${build.default_provider}"

  # Atlas does not support direct creation of SGs
  atlas:

  TerraGen:

