# Location for statefile in S3
terraform_config:
  tfvars_file:
    # Location where tfvars and config.tf file will be written to
    path: "C:/dev/python/terravarmer/tfvars"
    filename: ???
  s3_backend_key : "common/vpc/terraform.tfstate"


tfvars_config:
  instance_count              : 1
  instance_type               : "t3a.small"
  instance_name               : ???
  associate_public_ip_address : true
  ami_id                      : "ami-06310010cdfb6a743"
  public_subnet               : "${vpc.tfvars_config.public_subnets[0]}"
  tags:
    tag_business_owner            : "iain@test.com"
    tag_business_service_category : "C"
    tag_data_classification       : "Internal"
    tag_identifier                : ???

  security_group:
    sg_name                     : ???
    sg_description              : ???
    ingress_cidr_blocks         : ["0.0.0.0/0"]
    ingress_rules               : ["all-all"]

  key_pair:
    key_name                    : "labs-key"
    public_key                  : "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsYO2EwLo9GQxVoDKdxxQSNw/Y9bukRO6YNpc3MPmKPQorbpawHqYsq15j2/48dHJqP4VUgSwEEcpl/L5zeRRFGxbb3Unf5IdSvCA9aHZSAVfpHZaJVN7Nf0pC3eRKSfYvu166KpoienQg8aswXCgildLb5MDfl7ul6tfrjd/rbyty58Jp51fPKvqpKS0mUn5MT6ToECBtubCEJ9xqupQ5qQpKIHVleSUy+tSAxvYQTuMAmQfYEVQrJn9W9T5dsyWUi4X1MeEri4xqN8ZqaM8lhXmqp0f/Bsjpa15dMjTOkWDadu44dC3lPgB5yW5dcQMtrGMA2LpEvSFhy91iJ9xmw== rsa-key-20210324"
