module_metadata:
  aws_service: "key_pairs"
  name: "key_pair"
  lookup: "shared.key_pairs"
  resource_type: "aws_key_pair"

config:
  key_name: ???
  public_key: ???

outputs:
  key_name:
    description: "The name of the key"
    lookup: "${...module_metadata.lookup}.outputs.vpc_id"

# provider specific config can be added here
providers:
  # Set the provider that will create the infrastructure
  default_provider: "${build.default_provider}"

  # Atlas does not support creation of VPCs
  atlas:

  TerraGen:


    # Variables you want to add to outputs.tf file should be specified here


