defaults:
  - /aws/base/security_groups@: sg_base

#lookups:
#  vpc_id: "${shared.vpc.simple_vpc.module.lookup}.${shared.vpc.simple_vpc.outputs.vpc_id.lookup}"


config:
    name: "LocalAccessSG"
    description: "Access Instances from my local machine"
    vpc_id: "lookup: ${shared.vpc.simple_vpc.outputs.vpc_id.lookup}"
    tags:
      Name: "LocalAccessSG"
