# Variable definitions to write to tfvars file
config:
  vpc_name             : "hunter-labs-vpc"
  cidr                 : "10.0.0.0/16"
  azs                  : ["us-east-1a", "us-east-1b"]
  public_subnets       : ["10.0.100.0/24", "10.0.200.0/24"]
  enable_dns_hostnames : true

  tags:
    tag_environment : ${build.environment}

# provider specific config can be added here
providers:
  # Set the provider that will create the infrastructure
  default_provider: "${build.default_provider}"

  # Atlas does not support creation of VPCs
  atlas:

  terraform:
      s3_backend_key: "common/vpc/terraform.tfstate"
      tfvars_file:
        path: "C:/dev/python/terravarmer/tfvars"
        filename: "vars_simple_vpc.tfvars"
