module_metadata:
  aws_service: "ec2"
  name: "ec2"
  lookup: "app.ec2"
  resource_type: "aws_instance"

config:
  ami:                         "ami-06310010cdfb6a743"
  instance_type:               "t3a.small"

  subnet_id:                   ???
  associate_public_ip_address: false
  vpc_security_group_ids:      ???

  key_name:                    ???

  root_block_device:
    encrypted:                 true
    volume_type:               "gp3"
    volume_size:               8

  tags:
    Name:  ???
    Owner: "Hunter-Labs"

outputs:
  public_dns:
    description: "Public DNS address of instance"
    lookup: "${...module_metadata.lookup}.outputs.public_dns"
