# Order is important terravarmer will create infra in specified order specified in defaults object
defaults:
  # Shared Infrastructure
  - aws/shared/vpcs@shared.vpc: vpc_definitions/simple_vpc
#  - aws/shared/key_pairs@shared.hunter_labs_key: key_pair_definitions/hunter_labs_key
#  - aws/shared/security_groups@aws.shared.security_groups.enginetier: data_governance/dgv_enginetier

  # Application/Project specific Infrastructure
#  - aws/middleware/ec2@aws.application.ec2.instances.enginetier: data_governance/enginetier
#  - aws/middleware/ec2@middleware.ec2.servicetier: instance_definitions/servicetier
#  - aws/middleware/ec2@middleware.ec2.enginetier: instance_definitions/enginetier


# Provider overrides
#aws:
#  shared:
#    vpc:
#      providers:
#        default_provider: "terraform"

build:
  # Set to True to enable verbose debugging
  debug: True

  # The provider that will be used to create all infrastructure unless overidden in Provider Overrides above
  default_provider: "TerraGen"

  # Deployment environment must be one of dev|test|ppe|prod
  environment: "test"


provider_config:
  # This section allows for each provider to be configured, with specific values
  TerraGen:
    # If set to True terraform will apply the generated modules
    run_terraform: False

    # Terraform mode must be one of create|destroy
    terraform_mode: "create"
