# Order is important terravarmer will create infra in specified order specified in defaults object
defaults:
  # Shared Infrastructure
  - aws/shared/vpcs@shared.vpc.simple_vpc: vpc_definitions/simple_vpc
  - aws/shared/key_pairs@shared.key_pairs.hunter_labs_key: key_pair_definitions/hunter_labs_key
#  - aws/shared/security_groups@aws.shared.security_groups.enginetier: data_governance/dgv_enginetier

  # Application/Project specific Infrastructure
#  - aws/middleware/ec2@aws.application.ec2.instances.enginetier: data_governance/enginetier
#  - aws/middleware/ec2@middleware.ec2.servicetier: instance_definitions/servicetier
#  - aws/middleware/ec2@middleware.ec2.enginetier: instance_definitions/enginetier


# Provider overrides
#aws:
#  shared:
#    vpc:
#      providers:
#        default_provider: "terraform"

build:
  debug: True                   # Set to True to enable verbose debugging
  default_provider: "TerraGen"  # Provider used to create all infra unless overridden
  environment: "prod"           # Deployment environment must be one of dev|test|ppe|prod

  # Register providers here, required provider_name, and provider_location further provider specific
  # config can be added as needed
  registered_providers:
    TerraGen:
      module_location: "providers.aws.terragen.terragen_provider"
      properties:
        run_terraform: False      # Set to true for Terraform to apply created modules
        terraform_mode: "plan"  # Must be one of create|destroy|plan
        terraform_init_cmd: "terraform init --backend-config=/tools/terraform/config/backend_${build.environment}.config"
