# Order is important terravarmer will create infra in specified order specified in defaults object
defaults:
  # Shared Infrastructure
  - aws/shared/vpcs@shared.vpc.simple_vpc: simple_vpc
  - aws/shared/key_pairs@shared.key_pairs.hunter_labs_key: hunter_labs_key

  # Apps
  - aws/apps/sandbox@app.ec2.sandbox: sandbox


build:
  debug: True                      # Set to True to enable verbose debugging
  default_provider: "AWSProvider"  # Provider used to create all infra unless overridden
  environment: "prod"              # Deployment environment must be one of dev|test|ppe|prod
  shared_infra: "create"           # Process shared infra, Must be one of create|destroy|pass
  app_infra: "create"              # Process application infra, must be one of create|destroy|pass
  terraform_mode: "apply"          # Must be one of plan|apply - Plan produces terraform plan only, apply will create or destroy infra


environment:
  prod:
    aws_account: 222866594907
    region: "us-east-1"
    profile: "hunter_ops_prod"
    bucket: "hunter_ops_tfstate"