module_metadata:
  aws_service: "ec2"
  name: "sandbox"
  state_file: "shared/ec2/sandbox/terraform.tfstate"
  module_dir: "modules/aws/ec2"

config:
  # SG Config
  sg_name                     : "Sandbox SG"
  sg_description              : "SG for Sandbox Instance"
  ingress_cidr_blocks         : ["0.0.0.0/0"]
  ingress_rules               : ["all-all"]

  # EC2 Config
  instance_count              : 2
  instance_name               : "sandbox"
  associate_public_ip_address : True
  aws_account                 : ${build.aws_accounts[${build.environment}]}


lookups:
  key_pair_statefile  : ${shared.key_pairs.hunter_labs_key.module_metadata.state_file}
  vpc_statefile       : ${shared.vpc.simple_vpc.module_metadata.state_file}