defaults:
  - ec2_base

# Environment specific config that is injected at resolution time
environments:
  dev:
    instance_type: t3a.micro
  test:
    instance_type: t3a.micro
  prod:
    instance_type: t3a.large

# Overrides of ec2_base config
terraform_config:
  tfvars_file:
    filename: "enginetier.tfvars"
  s3_backend_key : "middleware/ec2/enginetier/terraform.tfstate"

tfvars_config:
  instance_name: "enginetier_${build.environment}"
  instance_type: "${enginetier.environments.${build.environment}.instance_type}"
  tags:
    tag_name: "enginetier"

  security_group:
    sg_name: "enginetier_sg"
    sg_description: "SG for Engine Tier"

  key_pair:
    key_name: "engine-key"
