defaults:
  - ec2_base

# Overrides of ec2_base config
terraform_config:
  tfvars_file:
    filename: "microtier.tfvars"
  s3_backend_key : "middleware/ec2/microtier/terraform.tfstate"


tfvars_config:
  instance_name: "microtier{build.environment}"
  tags:
    tag_name: "microtier"

  security_group:
    sg_name: "microtier"
    sg_description: "SG for microtier"

  key_pair:
    key_name: "micro-key"