defaults:
  - ec2_base

# Overrides of ec2_base config
terraform_config:
  tfvars_file:
    filename: "sandbox.tfvars"
  s3_backend_key : "middleware/ec2/sandbox/terraform.tfstate"


tfvars_config:
  instance_name: "sandbox_${build.environment}"
  tags:
    tag_name: "sandbox"

  security_group:
    sg_name: "sandbox_sg"
    sg_description: "SG for Sandbox"
