terraform_config:
  s3_backend_key : "common/vpc/terraform.tfstate"
  tfvars_file:
    path: "C:/dev/python/py-tfvars/tfvars"
    filename: "vars_simple_vpc.tfvars"

# Variable definitions to write to tfvars file
tfvars_config:
  vpc_name             : "hunter-labs-vpc"
  cidr                 : "10.0.0.0/16"
  azs                  : ["us-east-1a", "us-east-1b"]
  public_subnets       : ["10.0.100.0/24", "10.0.200.0/24"]
  enable_dns_hostnames : true

  tags:
    tag_environment : ${build.environment}
